set enc=utf-8
filetype off
set rtp+=~/.vim/bundle/Vundle.vim/
call vundle#rc()

Plugin 'gmarik/Vundle.vim'
Plugin 'tpope/vim-dispatch'

Plugin 'airblade/vim-gitgutter'
Plugin 'ctrlpvim/ctrlp.vim'
Plugin 'ervandew/supertab'
Plugin 'mhinz/vim-startify'
Plugin 'nathanaelkane/vim-indent-guides'
Plugin 'scrooloose/nerdcommenter'
Plugin 'scrooloose/nerdtree'
" Plugin 'scrooloose/syntastic'
Plugin 'w0rp/ale'

"Plugin 'sjl/gundo.vim.git'
Plugin 'tpope/vim-fugitive'
Plugin 'Xuyuanp/nerdtree-git-plugin'

" Colors
Plugin 'chumakd/ScrollColors'
"Plugin 'flazz/vim-colorschemes'

" Clojure treats
Plugin 'fireplace.vim'
Plugin 'junegunn/rainbow_parentheses.vim'

Plugin 'bling/vim-airline'
Plugin 'szw/vim-tags'
Plugin 'skwp/vim-rspec'
"Plugin 'majutsushi/tagbar'

" File syntax
Plugin 'jelera/vim-javascript-syntax'
Plugin 'elzr/vim-json'
Plugin 'ekalinin/dockerfile.vim'
" Plugin 'nanotech/jellybeans.vim'
" Plugin 'arcticicestudio/nord-vim'
" Plugin 'fatih/vim-go'

let g:indent_guides_auto_colors = 0
let g:indent_guides_start_level = 2

"let g:vim_tags_use_vim_dispatch = 1
let g:vim_tags_use_vim_dispatch = 1
let g:vim_tags_auto_generate = 0

hi IndentGuidesOdd  ctermbg=None
hi IndentGuidesEven ctermbg=black

let g:ale_lint_on_save = 1
let g:ale_lint_on_insert_leave = 0
let g:ale_lint_on_text_changed = 'never'

if &term == "screen-256color"
  if exists('$TMUX')
    let &t_SI = "\ePtmux;\e\e[5 q\e\\"
    let &t_EI = "\ePtmux;\e\e[2 q\e\\"
  else
    let &t_SI = "\e[5 q"
    let &t_EI = "\e[2 q"
  endif
endif

augroup rainbow_lisp
  autocmd!
  autocmd FileType lisp,clojure,scheme RainbowParentheses
augroup END

filetype plugin indent on " required!?
autocmd BufRead,BufNewFile * set indentkeys=0{,0},0),0],!^F,o,O,e

autocmd BufNewFile,BufRead *.go setlocal listchars=tab:\ \ 
autocmd FileType go setlocal noexpandtab tabstop=4 shiftwidth=4
autocmd FileType c,cpp,objc noremap <buffer><Leader>cc :ClangFormat<CR>

" lets ignore some shit directories
set wildignore+=*/vendor/*,*/tmp/*,*/data/*,*/log/*

" Avoid loc-list poping up when saving go files
" Let syntastic handle linting
" TODO: Check if this is still required
let g:go_fmt_fail_silently = 1

let g:ctrlp_working_path_mode = 'rac'
let g:ctrlp_cache_dir='~/.vim/ctrlp_cache'
let g:ctrlp_max_files=4000
let g:ctrlp_dotfiles = 0

let g:ctrlp_custom_ignore = {
  \ 'dir':  '\v[\/](\.(git|hg|svn)|node_modules|vendor|tmp|public|data)$',
  \ }

let g:airline#extensions#branch#enabled = 0
let g:airline#extensions#tagbar#enabled = 0
let g:airline#extensions#csv#enabled = 0
let g:airline#extensions#wordcount#enabled = 0

set statusline+=%#warningmsg#
"set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*

let g:airline_section_x = ''
" let g:airline_section_y = 'ss'
let g:airline_section_y = ''
let g:airline_skip_empty_sections = ''

let g:NERDSpaceDelims = 1
let g:NERDDefaultAlign = 'left'
let g:NERDCommentEmptyLines = 1
let g:NERDTrimTrailingWhitespace = 1

let NERDTreeIgnore = ['\~$', '\<node_modules\>']
let NERDTreeWinPos = 'right'
let NERDTreeQuitOnOpen = 3

let NERDTreeQuitOnOpen = 1
let NERDTreeChDirMode = 2
let NERDTreeMinimalUI = 1

set nocompatible

" visual shifting (does not exit Visual mode)
vnoremap < <gv
vnoremap > >gv
noremap Q <Nop>

noremap ]q :cnext<CR>
noremap [q :cprev<CR>

nnoremap <Leader>e :Hexplore!<RETURN>
"nnoremap <Leader>a :Vexplore<RETURN>
nnoremap <Leader>a :NERDTreeToggle<RETURN>
nnoremap <Leader>t :TagbarOpenAutoClose<CR>
nnoremap <Leader>u :GundoToggle<CR>

noremap . .`[

inoremap <Cr> <Esc>
nnoremap <Cr> i<Cr><Esc>
inoremap <Esc> a<Bs><Esc>u

"improve autocomplete menu color
highlight Pmenu ctermbg=238 gui=bold

set colorcolumn=100

set showfulltag
set timeout timeoutlen=1000 ttimeoutlen=100

set cpoptions=Adq$-
syntax on

set encoding=utf-8
" Allow backspace to go over autoindents, but not more.
set backspace=indent
set nowritebackup
set noswapfile
set clipboard+=unnamed
set fileformats=unix,dos,mac
set nohidden
set iskeyword+=_,$,@,%,#
set mouse=n

set hlsearch
set incsearch
set laststatus=2
set lazyredraw
set linespace=0
set list
set listchars=tab:>-,trail:~,extends:»,precedes:«
set matchtime=1
set novisualbell
set number
set numberwidth=4
set report=0
set scrolloff=3
set showmatch

set formatoptions=ocql
set nowrap
set expandtab
set shiftround
set shiftwidth=2
set softtabstop=2
set tabstop=8
" set smartcase

" reload vim configuration on write
"autocmd! bufwritepost .vimrc source %
