# Set colored prompt
PS1='\[\e[0;32m\]\h\[\e[m\]:\[\e[1;34m\]\W\[\e[m\]\[\e[1;32m\]\$\[\e[m\] \[\e[m\]'

export HISTCONTROL=ignoreboth:erasedups

# Our lovely linux terminal doesn't support 256 colors :(
if [ "$TERM" != "linux" ]; then
  TERM="xterm-256color"
fi

alias tmux='tmux -2'

# User specific aliases and functions
unset command_not_found_handle
